export const colors = {
  maroon: '#5B8DB8',
  maroonDark: '#3D6D94',
  maroonLight: '#7AACCE',
  gold: '#E8C94A',
  goldLight: '#F5E6A3',
  cream: '#F9FBFE',
  creamDark: '#EBF1F7',
  white: '#FFFFFF',
  text: '#1E3A50',
  textLight: '#6B8BA4',
  correct: '#2D6A4F',
  correctLight: '#D8F3DC',
  incorrect: '#C0392B',
  incorrectLight: '#FFE8E8',
};
